name: build

on:
  push:
    branches: [ "main", "build" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup msbuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: setup build information
      id: build
      run: .\.github\Get-BuildInfo.ps1 -ref '${{ github.ref }}' -event_name '${{ github.event_name }}' -configuration Release

    - name: build
      run: msbuild /m /p:Configuration=Release NetOfficeExtension.sln

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: NetOfficeExtension_${{ steps.build.outputs.app_version_full }}.vsix
        path: src/NetOfficeExtension/bin/Release/NetOfficeExtension.vsix
